### ISSUE TITLE
如何解决跨域问题

### ISSUE THREAD

**Issue by sun314cn** [ihanyang/cnode-vue#3]
您好,参照您的案例,出现如下问题:
Fetch API cannot load http://sun.vip.natapp.cn/dologin. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8090' is therefore not allowed access. The response had HTTP status code 502. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
抱歉,我才接触vue

**Comment by ihanyang** [comment]
可以试下 在服务器端加上 Access-Control-Allow-Origin header  或者 使用代理中转
